import 'pages/approve_forms_page/page.dart';
import 'pages/create_form_page/page.dart';
import 'pages/dashboard_page/page.dart';
import 'pages/employees_page/page.dart';
import 'pages/forgot_password_page/page.dart';
import 'pages/form_page/page.dart';
import 'pages/help_page/page.dart';
import 'pages/help_page/user_manual.dart';
import 'pages/login_page/page.dart';
import 'pages/logout_page/page.dart';
import 'pages/manage_forms_page/create_form/page.dart';
import 'pages/manage_forms_page/create_section/page.dart';
import 'pages/manage_forms_page/manage_form/page.dart';
import 'pages/manage_forms_page/page.dart';
import 'pages/notifications_page/page.dart';
import 'pages/profile_page/page.dart';
import 'pages/register_page/page.dart';
import 'pages/section_page/page.dart';
import 'pages/settings_page/page.dart';
import 'pages/unknown_route_page/page.dart';

export 'pages/approve_forms_page/page.dart';
export 'pages/create_form_page/page.dart';
export 'pages/dashboard_page/page.dart';
export 'pages/employees_page/page.dart';
export 'pages/forgot_password_page/page.dart';
export 'pages/form_page/page.dart';
export 'pages/help_page/page.dart';
export 'pages/help_page/user_manual.dart';
export 'pages/login_page/page.dart';
export 'pages/logout_page/page.dart';
export 'pages/manage_forms_page/create_form/page.dart';
export 'pages/manage_forms_page/create_section/page.dart';
export 'pages/manage_forms_page/manage_form/page.dart';
export 'pages/manage_forms_page/page.dart';
export 'pages/notifications_page/page.dart';
export 'pages/profile_page/page.dart';
export 'pages/register_page/page.dart';
export 'pages/section_page/page.dart';
export 'pages/settings_page/page.dart';
export 'pages/unknown_route_page/page.dart';

class Pages {
  static const String approveForms = ApproveFormsPage.routeName;
  static const String createForm = CreateFormPage.routeName;
  static const String dashboard = DashboardPage.routeName;
  static const String employees = EmployeesPage.routeName;
  static const String forgotPassword = ForgotPasswordPage.routeName;
  static const String form = FormPage.routeName;
  static const String help = HelpPage.routeName;
  static const String userManual = UserManual.routeName;
  static const String login = LoginPage.routeName;
  static const String logout = LogoutPage.routeName;
  static const String manageCreateSection = Manage_CreateSectionPage.routeName;
  static const String manageCreateForm = Manage_CreateFormPage.routeName;
  static const String manageManageForm = Manage_ManageFormPage.routeName;
  static const String manageForms = ManageFormsPage.routeName;
  static const String notifications = NotificationsPage.routeName;
  static const String profile = ProfilePage.routeName;
  static const String register = RegisterPage.routeName;
  static const String section = SectionPage.routeName;
  static const String settings = SettingsPage.routeName;
  static const String unknownRoute = UnknownRoutePage.routeName;
}
