name: smartshed
description: SmartShed Application for Diesel Loco Shed, Pune
publish_to: 'none' 

version: 1.1.3+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.6
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  intl: ^0.18.1
  go_router: ^12.1.1
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  printing: ^5.11.1
  pdf: ^3.10.7
  url_launcher: ^6.2.2
  flutter_localization: ^0.2.0
  syncfusion_flutter_pdfviewer: ^24.1.43
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.8
  envied_generator: ^0.5.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo/icon.png"
  min_sdk_version: 21
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/logo/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/
    - assets/images/
    - assets/logo/
    - assets/fonts/
    - assets/fonts/kohinoor.ttf
    - assets/fonts/kohinoor-bold.ttf

flutter_native_splash:
  color: "#eeeeee"
  color_dark: "#eeeeee"

  image: "assets/logo/logo.png"
  image_dark: "assets/logo/logo.png"

  image_android: "assets/logo/native-logo.png"
  image_dark_android: "assets/logo/native-logo.png"
  branding_android: "assets/logo/native-branding.png"
  branding_dark_android: "assets/logo/native-branding.png"

  android: true
  ios: true
  web: true

  android_12:
    color: "#eeeeee"
    color_dark: "#eeeeee"
    image: "assets/logo/native-logo.png"
    image_dark: "assets/logo/native-logo.png"
    branding: "assets/logo/native-branding.png"
    branding_dark: "assets/logo/native-branding.png"