name: smartshed
description: SmartShed application for Diesel Loco Shed, Pune
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.6
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  intl: ^0.18.1
  go_router: ^12.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo/icon.png"
  min_sdk_version: 21
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/logo/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/logo/
